### ISSUE TITLE
Files modified while being compared + specified download directory not used

### ISSUE THREAD

**Issue by aksskl** [AlexCSDev/PatreonDownloader#68] opened 2021-06-26 05:35 UTC
Windows

Deleted the previous installation and started fresh on 0.10.0

Files that have already been downloaded from previous runs are being modified. They aren't being altered but the date modified is changing. Is this intended and normal? If the program crashes mid scrape might it corrupt already downloaded files? I don't get why the already downloaded files are being written to instead of just being read. 

Also the specified directory isn't working. The command is  "--download-directory c:\path" right? The exe is using the default directory #AppDirectory#/downloads/#CreatorName# regardless of the command. (someone else reported this bug)

Also mega links are being weird, some work but most don't. Both single file links and folders. Maybe it's the restrictions but the most common error I get is

"The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters."

I'll look more into it maybe it's an issue on my end, but Gdrive works fine.

**Comment by AlexCSDev** [comment] 2021-06-26 13:43
> Files that have already been downloaded from previous runs are being modified. They aren't being altered but the date modified is changing. Is this intended and normal? If the program crashes mid scrape might it corrupt already downloaded files? I don't get why the already downloaded files are being written to instead of just being read.

That shouldn't happen. I'll take a look.

> Also the specified directory isn't working. The command is "--download-directory c:\path" right? The exe is using the default directory #AppDirectory#/downloads/#CreatorName# regardless of the command. (someone else reported this bug)

Yep, has been reported before.

> Also mega links are being weird, some work but most don't. Both single file links and folders. Maybe it's the restrictions but the most common error I get is

Known issue. You can either wait for the next version or place this file into **plugins** directory: https://mega.nz/file/z8dRTKoQ#uAkFlP7C7KBiBXqdjxGKBnlW2FrIoIpGkihUXx3MrcY. There might be still some issues with mega links even with this file (mostly when the same link posted more than in one post), those will be fixed in the next version.

**Comment by AlexCSDev** [comment] 2021-07-15 17:38
I can't replicate the behavior where old files are being altered. The only files which are being altered on all runs are .json and description files, but this is pretty much an intended behavior.

**Comment by aksskl** [comment] 2021-07-15 19:20
It's still happening for me. I moved the patreondownloader folder to another drive just in case that was the issue and it still happens. I'll try the new release tonight and report back.

**Comment by AlexCSDev** [comment] 2021-07-15 19:25
Alright, thank you

**Comment by AlexCSDev** [comment] 2021-07-15 22:49
I think I have reproduced it on my side, I'll take a look at it later

**Comment by aksskl** [comment] 2021-07-15 23:20
I see. Yeah, my next step was to try multiple creators. Thanks for doing that yourself.

**Comment by AlexCSDev** [comment] 2021-07-16 22:13
Alright, did some additional testing. patreonusercontent.com does not return content-length header which is required to check if existing file is changed or not. This results in all files from that domain being re-downloaded every time.

I will probably end up fixing this by adding command line option which will allow user to set what should be done when that happens (keep existing file, download remote file and compare, replace existing file without comparing)

**Comment by aksskl** [comment] 2021-07-17 00:30
Keep existing file sounds like a good default, and every so often run download remote and compare in case the creator revised something. Maybe in that instance it should backup the old file by adding the date it was replaced to the end of the filename or something appropriate like that. To keep old files alongside new ones instead of replacing.

**Comment by WindedHero** [comment] 2021-07-24 14:10
if `--overwrite-files` is `false` by default, this should not happen regardless of any returned content-length header, right? The file already exists, it should not be overwritten.

I'm dealing with this same bug and it turns big jobs into lengthy ordeals because it downloads every single thing over again.

**Comment by AlexCSDev** [comment] 2021-07-24 14:34
I think with the current logic it will ignore `--overwrite-files` if the content-length is 0 or missing

**Closed** 2021-08-01 13:15 UTC
Labels: bug

**Comment by AlexCSDev** [comment] 2021-08-01 13:31
Added ability to control behavior of the downloader when remote file size is not available. Please refer to release notes for additional information.
