### ISSUE TITLE
Filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by WindedHero** [AlexCSDev/PatreonDownloader#87] opened 2021-10-03 14:05 UTC
PatreonDownloader seems to be trying to download files and save them with names that are too long, and it is causing multiple "retries limit reached" errors. 

`2021-10-03 09:56:53.5854 DEBUG Encountered IO error while trying to access https://www.patreon.com/media-u/Z0FBQUFBQmhXYlZkRGh4TktmS0lub1JFVTNGWlB2cWhYX0hLd2VaeUg0R3ZMLXZDOGVBVkYtdnRRaGVGLVdLaFhYOW1tc2pLN3JXN1lxZi1uWElTc3NjQzFIWEg4VWlma3R3OU1LbUY4bEhBS1ZveVVXR1RLU1d5dG5odTRxZG9PYmx3UFNlbVh1eDBBdV9GbWlQYVl2UmpQaFBRZTctNDFRPT0=, retrying in 50 seconds (0 retries left)... The error is: System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'E:\Download\[28199339] 2019-07-07 ???????\media_https___www.patreon.com_media-u_Z0FBQUFBQmhXYlZkMERUNnkwU2RwN2hVY0ttd0dsYzBQQy1yYzhxZXVhNXFMNnp5VzZRSFRENnQ3cVhleS1HMWx6RDdTVTlidEgtNGtfUFBqVEJnd1FLOThaNkxxZEV5RllkeTFzQ1cwQVUzVDdYYjhTbDROa1V5cjVVaG4xRmg1UTlteE95eVl3NXM0Q0NCcWVPV3MyZWsyUHc0a1U2Wml3PT0='
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at UniversalDownloaderPlatform.DefaultImplementations.WebDownloader.DownloadFileInternal(String url, String path, Boolean overwrite, Int32 retry, Int32 retryTooManyRequests) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.DefaultImplementations\WebDownloader.cs:line 253`

**Comment by AlexCSDev** [comment] 2021-10-03 16:36
Please send page*.json files to alexcsdev@protonmail.com.

**Comment by AlexCSDev** [comment] 2021-10-03 17:17
Alright, I think I see where the problem is, will try to figure out how to fix it properly.

**Comment by AlexCSDev** [comment] 2021-10-04 21:13
Fixed in 0.10.1.1

**Closed by AlexCSDev** 2021-10-04 21:13 UTC
Labels: bug
